---
# Run all notebooks on every push
name: "üóíÔ∏è Build notebooks"
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    types:
      [opened, reopened, edited]

jobs:
  build:
    name: "Build and test"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Setup PDM for build commands"
        uses: pdm-project/setup-pdm@v3

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pdm export -o requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install .
          pip install pytest nbmake

      - name: "Build notebooks: pytest"
        run: pytest --nbmake examples/quick_temp_score_calculation.ipynb
