---
name: "Pre-Release (Publish to Test PyPI)"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Build Validation"
    runs-on: "ubuntu-latest"
    strategy:
    matrix:
      python-version: ['3.9', '3.10', '3.11']
    steps:

      - name: "Checkout Repository"
      - uses: actions/checkout@v3

      - name: "Populate/Export Environment Variables"
        id: variables
        run: |
          datetime=$(date +'%Y%m%d%H%M')
          export datetime
          echo "$datetime" >> "$GITHUB_OUTPUT"

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: "Build with TOX"
        run: |
          tox -e build

      - name: "Tag Test Release"
        run: |
          git tag v0.0.${{ steps.variables.outputs.datetime }}\
          -${{ matrix.python-version }}
          git checkout tags/v0.0.${{ steps.variables.outputs.datetime }}\
          -${{ matrix.python-version }}

      - name: "Publish Build Products"
        run: |
          echo "Pre-release process completed"
          echo "Publishing development binary files..."

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            dist/*.tar.gz
            dist/*.whl

      - name: "Publish Artefacts to Test PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
