---
name: "pre-release"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre-Release"
    runs-on: "ubuntu-latest"
    strategy:
    matrix:
      python-version: ['3.9', '3.10', '3.11']
    steps:

      - name: "Populate/Export Environment Variables"
        id: variables
        run: |
          datetime=$(date +'%Y%m%d%H%M')
          export datetime
          echo "$datetime" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: "Build the Project with TOX"
        run: |
          tox -e build

      - name: "Tag Test Release"
        run: |
          git tag v0.0.${{ steps.variables.outputs.datetime }}-${{ matrix.python-version }}

      - name: "Build and Test"
        run: |
          echo "Pre-release process completed"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            dist/*.tar.gz
            dist/*.whl

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
